swagger: '2.0'
info:
  title: BRAvo API
  description: API description in **Markdown**.
  version: 1.0.0
host: vm0131.france-bioinformatique.fr
schemes:
  - http
  - https
paths:
  /automatic/upstream:
    post:
      summary: Run upstream assembly
      description: Returns an upstream regulation graph based on a list of target genes.
      parameters:
        - in: formData
          name: genes
          type: array
          required: true
          items:
            type: string
            format: json
            enum:
              - '[MYC,GALT]'
              - '[ENSG00000158669,HGNC:4135,ENSG00000116133]'
          description: A person's name.
        - in: formData
          name: type
          type: string
          required: true
          enum:
            - id
            - name
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      responses:
        '200':
          description: OK
  /automatic/downstream:
    post:
      summary: Run downstream assembly
      description: Returns a downstream regulation graph based on a list of source genes.
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: OK
